### ISSUE TITLE
general top down R workflow

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#4]
This is just to describe general topDownR workflow. New version

1) create an MS2 method. Each fragmentation condition is ENCODED with the target mz. E.g. for 500.1 becomes 500.1001 
2) acquire data: each spectrum is protein fragmented at a particular condition.
3) extract information from raw files using scansHeadsMan. It generates two files: METHOD table (just description of fragmentation conditions) and SCANHEADER (information on individual spectra) 
4) Apply Xtract to each file and generate deconvoluted mzML from every file
5) Assemble ProtFragOpt object. The following information goes into it:
a) METHOD and SCANHEADER tables are combined based on the code of mz target
b) mzML contains scans
c) protein seqeunce file is used to generate theoretical spectrum

**Comment by pavel-shliaha** [comment]
We need to create a new workflow figure for Figure 1 of the paper. Attached here is the figure I preliminary agreed on with Ole. I have also put a presentation in 

Google Drive\example_files_for_topDown\figure_1

so you dont have to type the text. 

![capture](https://user-images.githubusercontent.com/1895805/31457418-f915aef2-aebc-11e7-94d2-3f41b16e9a70.JPG)

**Comment by sgibb** [comment]
So in fact something like this (that are just the default settings, please tell me if the box shape, (text-/background-)color, ... should be modified):

![figure1 mmd](https://user-images.githubusercontent.com/1828443/31684921-89e81b9a-b381-11e7-9acd-cd86bf252f25.png)

mermaid code: https://gist.github.com/sgibb/a4e5433a386729e03591642e0e1fad7e
