### ISSUE TITLE
try different encoding strategies for mz 

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#47]
we have a problem that oftentimes an incorrect mz is recorded in the filter string. This can have different origin, e.g. rounding errors in the instrument. Hence I will try different new strategies for encoding:

Strategy 1: 

increase the mz difference between successive scans. We have up to 250 experiments. We are willing to accept a 0.05-0.1 Da shift overall. I.e. we can go as far as having 0.0002 - 0.0004Da in shift

Strategy 2:

increase the mz even higher but recycle. E.g.

we can do: 0.01, 0.02, 0.03, 0.04, 0.05 and then recycle

I will test this shortly

**Comment by pavel-shliaha** [comment]
In the newly released version of software the bug with the labeling has been fixed. Now even 0.0001 works perfectly

**Comment by pavel-shliaha** [comment]
no its not. Unfortunately after testing on mz 1162 the software still awards incorrect mz, Interestingly this does not happen on lower masses. Will test higher mz increments with higher mz shortly

**Comment by sgibb** [comment]
Superseeded by `ScanDescription`
