### ISSUE TITLE
computation of conditions bug

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#52]
If I execute the following code I get 

```r
myoTD <- readTopDownFiles(path = getwd(),
                          type = c("b", "c", "y", "z"),
                          adducts = data.frame(mass=c(-H, H), name=c("cmH", "zpH"), to=c("c", "z")),
                          neutralLoss = NULL,
                          modifications = NULL,
                          sampleColumns = sampleColumns) 
myoTD <- filterInjectionTime(myoTD, maxDeviation=log2(3), keepTopN=2)
myoTD <- filterIntensity(myoTD, threshold=0.1)
myoTD <- filterCv(myoTD, threshold=30)
myoTD <- filterNonReplicatedFragments(myoTD)
ncb <- as(myoTD, "NCBSet")
ncbRed <- ncb[,ncb$AgcTarget == 5e5 & ncb$EtdReagentTarget %in% c(1e7, 0) & ncb$Mz == 707.3,]
ncbRedCond <- as.data.frame (bestConditions(ncbRed), stringsAsFactors = FALSE)
ncbRedCond["conditions"] <- row.names (ncbRed@colData)[ncbRedCond$index]
conditions

#   index bonds                              conditions
#1     95    90  C0707.30_5.0e+05_1.0e+07_07_05.00_00_1
```
so the best condition is index 95 with 90 bonds. However this is not the case: the best condition is 131 with 93 fragments 
```r
xx <- ncbRed@assay[, c(131, 95)]
sum(xx[, 1] == 1, xx[, 1] == 2, 2*sum(xx[, 1] == 3))
sum(xx[, 2] == 1, xx[, 2] == 2, 2*sum(xx[, 2] == 3))
```

C131 gives 93 and C95 gives 92 fragments. I imagine its a simple bug of not awarding 2 points for "Both" fragment (3 in your case)?

**Comment by pavel-shliaha** [comment]
right now the  bestConditions() returns a table with the number of fragments covered + index. I know we discussed this and I know I asked for fragments not bonds, but it seems the field requires to maximise bonds not fragments. Could you please now compute both: bonds covered and fragments number and introduce an argument, maximise = "bonds" or "fragments", with "fragments" as default. If "fragments"  is selected as in now,the conditions are listed in order of increasing fragments if "bonds" are selected the conditions are returned in order of maximising bonds covered. However metrics are always returned

**Comment by sgibb** [comment]
I have a question regarding the final reporting table. The current approach is:

1. Find the highest fragment coverage (easy to change to highest bond coverage; I already did that.)
2. Remove the fragments from the whole dataset (easy to change for bonds)
3. Start at 1. again until now additional coverage could be generated.
4. Report results.

The problem is in the implementation of step 2. Image the following conditions:

||cond1|cond2|
|--|--|--|
|bond1|C|-|
|bond2|N|B|

maximise fragments:

1. Select cond1 or 2 based on intensity (e.g. we select cond1)
2. Remove C from bond1 and N from bond2 (turn B in cond2 into a C).
3. Select cond2 which adds a C:
4. Report

|index|fragments|bonds|
|--|--|--|
|1|2|2|
|2|1|?|

The question is what should be reported for the `?` in the table above? 1 because the C covers 1 bond (then the colSum would be larger than the real number of bonds). Or zero because the bond is already covered by condition 1 (then the colSum would be equal to the real bond number, but some fragments won't cover a bond)?

same problem for maximise bonds is IMHO easy:

1. Select cond1 because it covers 2 bonds.
2. Remove both bonds from the coverage set
3. Nothing left
4. Report

|index|fragments|bonds|
|--|--|--|
|1|2|2|

**Comment by pavel-shliaha** [comment]
In your example, the answer we are looking for is

index | fragments | bonds
-- | -- | --
1 | 2 | 2
2 | 1 | 0

however, what is important attempting to maximise bonds will generate a different optimal combination than attempting to maximise fragments. Hence we need an argument: maximise = "bonds" or  "fragments" However in both cases (if possible, I would prefer to have both columns: fragments and bonds) calculated.

I know this is not what I initially wanted, but it seems the field requires to report coverage in terms of bonds, however, I would still like to have the fragment functionality calculated

**Comment by sgibb** [comment]
As we discussed via skype we optimise for number of fragments (default) or bonds. If there are multiple conditions with the same number of fragments/bonds we choose the one with the highest overall intensity. The bonds (fragments) are ignored for optimisation if `maximise="fragments"` (`maximise="bonds"`) but reported.

```r
library("topdownr")
data(tds)
tds <- aggregate(tds)
ncb <- as(tds, "NCBSet")

bestConditions(ncb, maximise="fragments")
#                                index fragments bonds
# C1.0e+06_0.0e+00_00.00_00_14_1   219        99    98
# C1.0e+06_1.0e+06_05.00_21_00_1   160        36    31
# C1.0e+06_1.0e+06_02.50_00_21_1   154         9     6
# C1.0e+06_1.0e+06_15.00_14_00_1   181         5     2
# C1.0e+06_1.0e+06_02.50_00_07_1   152         5     4
# C5.0e+05_0.0e+00_00.00_00_21     144         4     1
# C1.0e+06_1.0e+06_02.50_00_14_1   153         3     2
# C1.0e+06_1.0e+06_10.00_00_21     176         3     1
# C1.0e+06_1.0e+06_10.00_21_00_1   171         2     0
# C5.0e+05_1.0e+06_10.00_00_00_1   104         2     0
# C1.0e+06_1.0e+06_15.00_00_14     186         2     2
# C5.0e+05_0.0e+00_00.00_35_00_1   141         1     0
# C1.0e+05_1.0e+06_02.50_00_00_1    11         1     0
# C1.0e+06_1.0e+06_10.00_28_00     172         1     0
# C1.0e+06_1.0e+06_05.00_28_00_1   161         1     1
# C5.0e+05_1.0e+06_05.00_00_07_1    88         1     1
# C1.0e+06_1.0e+06_30.00_00_00     201         1     0
# C1.0e+06_1.0e+06_10.00_00_07     174         1     0
# C5.0e+05_1.0e+06_15.00_07_00     105         1     0
# C5.0e+05_1.0e+06_02.50_00_21_1    79         1     0
# C1.0e+06_1.0e+06_10.00_00_14     175         1     0
# C5.0e+05_1.0e+06_10.00_00_14_1   100         1     0
# C5.0e+05_1.0e+06_50.00_28_00     130         1     0
# C5.0e+05_0.0e+00_00.00_07_00_1   137         1     0
# C1.0e+06_1.0e+06_10.00_00_35_1   178         1     0
# C1.0e+06_0.0e+00_00.00_21_00_1   215         1     0
bestConditions(ncb, maximise="bonds")
#                                index fragments bonds
# C1.0e+06_0.0e+00_00.00_00_14_1   219        99    98
# C1.0e+06_1.0e+06_10.00_00_07     174        35    32
# C1.0e+06_1.0e+06_05.00_00_07     163         5     5
# C5.0e+05_0.0e+00_00.00_35_00_1   141         6     3
# C1.0e+06_1.0e+06_10.00_28_00     172         2     2
# C1.0e+06_1.0e+06_05.00_28_00_1   161         4     2
# C5.0e+05_1.0e+06_05.00_00_14_1    89         4     2
# C5.0e+05_1.0e+06_02.50_00_21_1    79         3     2
# C5.0e+05_1.0e+06_05.00_00_07_1    88         2     1
# C1.0e+06_1.0e+06_02.50_00_07_1   152         2     1
# C1.0e+06_1.0e+06_15.00_00_14     186         1     1
```

**Comment by pavel-shliaha** [comment]
If possible could you please introduce 2 additional columns containing the total number of  fragments and bonds covered in every condition. So now there will be 5 columns:

1) "index"
2) "fragments_added_to_combination"
3) "bonds_added_to_combination"
4) "fragments_in_codnition"
5) "bonds_in_condition"

this will make the table more infromative

**Comment by sgibb** [comment]
Now there are 5 columns:
```r
library("topdownr")
data(tds)
tds <- aggregate(tds)
ncb <- as(tds, "NCBSet")

bestConditions(ncb, maximise="fragments", n=10)
#                                Index FragmentsAddedToCombination
# C1.0e+06_0.0e+00_00.00_00_14_1   219                          97
# C1.0e+06_1.0e+06_05.00_21_00_1   160                          37
# C1.0e+06_1.0e+06_02.50_00_07_1   152                           9
# C1.0e+06_1.0e+06_02.50_00_21_1   154                           6
# C1.0e+06_1.0e+06_15.00_14_00_1   181                           5
# C5.0e+05_0.0e+00_00.00_00_21     144                           4
# C1.0e+06_1.0e+06_02.50_00_14_1   153                           3
# C1.0e+06_1.0e+06_10.00_00_21     176                           3
# C1.0e+06_1.0e+06_10.00_21_00_1   171                           2
# C5.0e+05_1.0e+06_10.00_00_00_1   104                           2
#                                BondsAddedToCombination FragmentsInCondition
# C1.0e+06_0.0e+00_00.00_00_14_1                      96                   97
# C1.0e+06_1.0e+06_05.00_21_00_1                      32                   89
# C1.0e+06_1.0e+06_02.50_00_07_1                       8                   90
# C1.0e+06_1.0e+06_02.50_00_21_1                       3                   90
# C1.0e+06_1.0e+06_15.00_14_00_1                       2                   75
# C5.0e+05_0.0e+00_00.00_00_21                         1                   29
# C1.0e+06_1.0e+06_02.50_00_14_1                       2                   67
# C1.0e+06_1.0e+06_10.00_00_21                         1                   62
# C1.0e+06_1.0e+06_10.00_21_00_1                       0                   86
# C5.0e+05_1.0e+06_10.00_00_00_1                       0                   63
#                                BondsInCondition
# C1.0e+06_0.0e+00_00.00_00_14_1               96
# C1.0e+06_1.0e+06_05.00_21_00_1               88
# C1.0e+06_1.0e+06_02.50_00_07_1               90
# C1.0e+06_1.0e+06_02.50_00_21_1               87
# C1.0e+06_1.0e+06_15.00_14_00_1               71
# C5.0e+05_0.0e+00_00.00_00_21                 29
# C1.0e+06_1.0e+06_02.50_00_14_1               66
# C1.0e+06_1.0e+06_10.00_00_21                 62
# C1.0e+06_1.0e+06_10.00_21_00_1               83
# C5.0e+05_1.0e+06_10.00_00_00_1               62
```
```
