### ISSUE TITLE
Provide argument to injection time filtering to split 

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#66]
The software allows to filter on injection times. However a following situation is possible: a user acquires the data but then decides on acquiring more conditions later on (happened to  me with the UVPD addition to the CA dataset). Then the user might prepare the protein solution slightly differently so that the resulting  solution is slightly more or less intense, as a result the injection time filtering on the whole dataset no longer works. 

It would be great if the dataset can be divided into groups for calculation of injection times. This could be a a simple vector with numbers corresponding to groups

e.g.  we have 4 files

file1
file2
file3
file4

if we wanted files 1 and 2 to be in group 1,, file 3 and 4 in separate groups we could write

c(1, 1, 2, 3) 

by default it would be c(1, 1, 1, 1)

**Comment by sgibb** [comment]
Sorry but I don't completely understand where I should add this functionality. Currently we do the following:

1. Calculate the median injection time depending on `Mz` and `AgcTarget`.
2. Calculate the `log2(IonInjectionTimeMs / MedianIonInjectionTimeMs)`.
3. Keep the `keepTopN` technical replicates per `Sample` with the lowest deviatiation.

Should I add the file group argument to the first step (calculation of the median ion injection time)?

**Comment by pavel-shliaha** [comment]
yes, you are right step 1

**Comment by sgibb** [comment]
I would provide an argument to `filterInjectionTime(..., by=Sample, medianBy=c("Mz", "AgcTarget"))` and than you could overwritte the `medianBy` argument. Ok?

**Comment by pavel-shliaha** [comment]
so you mean I can specify the columns which I use to calculate the median, using medianBy? This is a good solution, but then why do I need by = sample?

**Comment by sgibb** [comment]
For the `keepTopN` argument (keep the top n (minimal deviation) technical replicates).

**Comment by pavel-shliaha** [comment]
what does by = sample do exactly? Is sample fragmentation condition number?

**Comment by sgibb** [comment]
It is defined by the user in `readTopDownFiles` and is more or less a specific condition (number):
https://github.com/sgibb/topdownr/blob/32a2c150059e5a63230dbab2642d7643476568c5/R/functions-TopDownSet.R#L105-L109

**Comment by pavel-shliaha** [comment]
Ok, sorry. If I can specify medianBy, then this indeed solves the problem

**Comment by sgibb** [comment]
As we decided in our skype chat we don't provide an argument to `filterInjectionTime` but a new method `updateMedianInjectionTime`. Now you can call:
```r
tds <- readTopDownFiles("CA")
tds <- updateMedianInjectionTime(tds, by=c(1, 1, 2, 3)) # your example above
tds <- filterInjectionTime(tds)
```
