### ISSUE TITLE
not all runs have all fragmentation methods

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#68]
I have tried to load some UVPD data in and it appears that this lines of code are causing the issue:

```

d$EtdActivation[d$Activation1 == "ETD"] <-
  d$Energy1[d$Activation1 == "ETD"]
d$CidActivation[d$Activation1 == "CID"] <-
  d$Energy1[d$Activation1 == "CID"]
d$CidActivation[d$Activation2 == "CID"] <-
  d$Energy2[d$Activation2 == "CID"]
d$HcdActivation[d$Activation1 == "HCD"] <-
  d$Energy1[d$Activation1 == "HCD"]
d$HcdActivation[d$Activation2 == "HCD"] <-
  d$Energy2[d$Activation2 == "HCD"]


d$Activation <-  topdownr:::.fragmentationMethod(d[, paste0(c("Etd", "Cid", "Hcd"), "Activation")])

Error in `[.data.frame`(d, , paste0(c("Etd", "Cid", "Hcd"), "Activation")) : 
  undefined columns selected

```
thi s happens because there are no ETciD or EThcD methods in the UVPD methods I created. 

@sgibb could you please modify the code with the expectation that not every file has all fragmentation methods?

**Comment by sgibb** [comment]
I didn't look at the example file yet but how do we define `UvpdActivation`? Is there `Activation2 == "UVPD"` and `Energy2` again?
