### ISSUE TITLE
Provide a method to combine TopDownSets

### ISSUE THREAD

**Issue by sgibb** [sgibb/topdownr#69]
If the user loads two different `TopDownSet`s it should be possible to combine them (if the `rowData` (fragment data) are identical it is more or less just a `cbind` for the `assay` `matrix` and an `rbind` for the `colData` `data.frame`), e.g.:
```r
tds1 <- readTopDownFiles("my-cid-hcd-files/")
tds2 <- readTopDownFiles("my-upvd-files/")

tds <- combine(tds1, tds2)
```

**Comment by pavel-shliaha** [comment]
could you please implement a method to combine NCBsets see issue #71? 

It currently returns an error:

Order of conditions changed.
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘updateMedianInjectionTime’ for signature ‘"NCBSet"’

**Comment by sgibb** [comment]
This was indeed a bug. It is fixed now (but that doesn't mean that your attempt from #71 works).
