### ISSUE TITLE
redundant fragment matching

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#72]
I think we might have discussed this before but I need to know for the paper. What happens if:

1) an mz can be matched to two or more fragments with specified tolerance
2) a fragment can be matched to two or more mz with specified tolerance

I think we need to reflect the bhaviour in readTopDownFiles with default of removing these  matches

**Comment by sgibb** [comment]
1. The nearest is choosen (if the difference is numerical equal, than depending on the internal numeric representation (depending on R and the platform, e.g. Linux/Windows, so more or less unpredictable))
```r
## the second fragment is choosen
topdownr:::.matchFragments(1.5, 1:2, tolerance=1)
[1]  2
## the first fragment is choosen
topdownr:::.matchFragments(2.5, 2:3, tolerance=1)
[1] 2
```
2. We choose always the one with the lowest mz:
```r
topdownr:::.matchFragments(1:2, 1.5, tolerance=1)
[1]  1 NA
topdownr:::.matchFragments(2:3, 2.5, tolerance=1)
[1]  1 NA
```

> I think we need to reflect the bhaviour in readTopDownFiles with default of removing these matches

So I should remove all duplicated matches (regardless whether type 1 or type 2 happens)?

**Comment by pavel-shliaha** [comment]
I think it should be 2 separate arguments, smth like

1) redundantIonMatch  = c("lowest_difference", "remove")
2) redundantFragmentMatch = c("lowest_difference", "remove")

default behavior should be remove, I think but I need to test this

**Comment by sgibb** [comment]
Now `readTopDownFiles` has two new arguments: `redundantIonMatch`, `redundantFragmentMatch`. Both could be `"remove"` (default) or `"closest"`. 
For the myoglobin dataset we now get the following number of matches:

remove/remove: 368296 
closest/closest: 372991 (same number as before, closest/closest was the original default)

```r
topdownr:::.matchFragments(1.5, 1:2, tolerance=1, redundantIonMatch="remove")
# [1] NA

topdownr:::.matchFragments(1.5, 1:2, tolerance=1, redundantIonMatch="closest")
# [1] 2

topdownr:::.matchFragments(1:2, 1.5, tolerance=1, redundantFragmentMatch="remove")
# [1] NA NA

topdownr:::.matchFragments(1:2, 1.5, tolerance=1, redundantFragmentMatch="closest")
# [1]  1 NA
```

Do we really need two arguments? Wouldn't be `redundantMatches=c("remove", "closest")` be enough. Does anybody want to use remove/closest or closest/remove instead of remove/remove, closest/closest?

Please note that currently `plot` doesn't accept/respect these arguments and silently uses the default remove/remove settings.

**Comment by pavel-shliaha** [comment]
great! Actually I think we do.

1) those are different questions. I can for example say: I want the ion to be matched to the closest fragment if I get 2 fragments, but I dont want the fragment to be matched to the closest ion
2) we are actually developing very novel software and we cannot say at the moment what should be done with this redundant matching. By providing these arguments we allow users to test this

**Comment by sgibb** [comment]
I agree. Now the redundant matching strategies are respected by `plot` and mentioned in the log information. Please note that I added a new slot to the `TopDownSet` class and so saved objects have to be reimported.
