### ISSUE TITLE
new approach to making methods (expose the data.frame of modifications)

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#77]
Currently the approach we take to fragmentation optimisation is this:

1) create combinations of settings that the user provides (stored in intermediate data.frame)
2) remove nonsensical combinations
3) create an XML to make method 
4) create a .meth file

There is a couple of problems with step number 1:

1) since when you add more fragmentation conditions the potential number of meaningless combinations increases dramatically. For example we already have around 3000 scans of which 1200 are nonsensical. If we add 10 UVPD times this will really create a combinatorial explosion. 
2) a user might not want all the combinations. For example a user will probably prefer to target low charge states for HCD, but high charge states for ETD. Currently it is not possible to do this, since the data.frame with the conditions is hidden. 

A good solution to both this issues is expose the underlying table and make it modifiable, and also add the possibility to combine these tables. So that a user can for example create a separate data.frame for HCD, ETD and UVPD and combine them. Importantly this would mean that the tables might have different number of columns and different column names

We can still have a function that checks the method table and remove nonsensical combinations before passing it onto the function that creates the XML. The function that creates the XML should still have all the underlying parameters it had previously (number of replicates, randomisation, labelling conditions by mz, modifications to MS1). However, the function name should be called to smth like writeMethodXmlFragOptim

**Comment by pavel-shliaha** [comment]
The suggested workflow 

![new_workflow](https://user-images.githubusercontent.com/1895805/45928166-6ef20600-bf3f-11e8-8b24-21f1470266e4.PNG)

however as you pointed out it can lead to a large number of combinations, for example the fragmentation parameters in the example below result in around 8mln fragmentation conditions and filtering becomes very long. To speed things us a user can create several dataframes, unique to each fragmentation type and then combine them without performing any filtering

`setwd ("M:\\r_scripts\\2018_09_18_topdownr_2")

parMS1 <- list ("FirstMass" = 400, "LastMass" = 1200, "Microscans" = 10)

parMS2ALL  <- list (# targeted mz
                    "TargetMz" =  c(560.6, 700.5, 933.7), 
  
                    # common paramters
                    "OrbitrapResolution" = "R120K", 
                    "IsolationWindow" = 1, 
                    "MaxITTimeInMS" = 200,
                    "Microscans" = 40,
                    "AgcTarget" = c(1e5, 5e5, 1e6),
                    
                    # fragmentation paramters
                    "ActivationType" = c("CID", "HCD",  "ETD", "UVPD"),     
                    
                    # CID
                    "CIDCollisionEnergy" = c(NA, seq (7, 35, 7)) , 
                    
                    # HCD
                    "HCDCollisionEnergy" = c(NA, seq (7, 35, 7)), 
                    
                    # ETD
                    "ETDReagentTarget" = c(NA, 1e6, 5e6, 1e7),
                    "ETDReactionTime" = c (NA, 2.5, 5, 10, 15, 30, 50),
                    "ETDSupplementalActivation" = c(NA, "ETciD", "EThcD"),
                    "ETDSupplementalActivationEnergy" = c(NA, seq (7, 35, 7)), 
                   
                    # UVPD
                    "UVPDActivationTime" = c(NA, seq (5, 50, 5)))


paramCombTable <- expand.grid (parMS2ALL)
paramCombTable <- removeNonsensicalCombinations(paramCombTable)





removeNonsensicalCombinations <- function(parMS2){
  
  activationTypeFilter <- sapply (c("CID", "HCD", "ETD", "UVPD"), function(x) NULL) 
  for (i in 1:length(activationTypeFilter )) activationTypeFilter [[i]] <- sapply (c("expectedNA", "notNA"), function(x) NULL)
  
  #CID filtering
  activationTypeFilter$CID$notNA <- c("CIDCollisionEnergy")
  
  activationTypeFilter$CID$expectedNA <- c("HCDCollisionEnergy", "ETDReagentTarget", "ETDReactionTime", "ETDSupplementalActivation", 
                                          "ETDSupplementalActivationEnergy", "UVPDActivationTime")
  
  #HCD filtering
  activationTypeFilter$HCD$notNA <- c("HCDCollisionEnergy")
  
  activationTypeFilter$HCD$expectedNA <- c("CIDCollisionEnergy", "ETDReagentTarget", "ETDReactionTime", "ETDSupplementalActivation", 
                                          "ETDSupplementalActivationEnergy", "UVPDActivationTime")
  
  #ETD filtering
  activationTypeFilter$ETD$notNA <- c("ETDReagentTarget", "ETDReactionTime", "ETDSupplementalActivation", "ETDSupplementalActivationEnergy")
  
  activationTypeFilter$ETD$expectedNA <- c("CIDCollisionEnergy", "HCDCollisionEnergy", "UVPDActivationTime")
  
  #UVPD filtering
  activationTypeFilter$UVPD$notNA <- c("UVPDActivationTime")
  
  activationTypeFilter$UVPD$expectedNA <- c("CIDCollisionEnergy", "HCDCollisionEnergy", "ETDReagentTarget", "ETDReactionTime", "ETDSupplementalActivation", 
                                          "ETDSupplementalActivationEnergy")
  
  
  message (paste ("initial number of lines", nrow (parMS2)))
  for (i in 1:length (activationTypeFilter)){
    
    activatioTypeBoolean  <- parMS2$ActivationType == names (activationTypeFilter)[i] 
    expectedNABoolean     <- apply (parMS2[activationTypeFilter[[i]]$expectedNA], 1, function(x) any (!is.na (x)))
    notNABoolean          <- apply (parMS2[activationTypeFilter[[i]]$notNA], 1, function(x) any (is.na (x)))
    
    removeLines <- activatioTypeBoolean & (expectedNABoolean|notNABoolean)
    
    parMS2 <- parMS2[!(removeLines), ]
  }
  
  message (paste ("final number of lines", nrow (parMS2)))
  
  return (parMS2)
}
`

**Comment by sgibb** [comment]
What do you think about building the `data.frame` for each ActivationType separately instead of removing useless combination afterwards. Here is a working example (downloads the "xml" branch of `topdownr` where I am going to implement the new functionality):
```r
devtools::install_github("sgibb/topdownr@xml")
library("topdownr")

expandMs1Conditions(FirstMass=400, LastMass=1200, Microscans=as.integer(10))
#   FirstMass LastMass Microscans
# 1       400     1200         10

targetMz <- cbind(mz=c(560.6, 700.5, 933.7), z=rep(1, 3))
common <- list(
    OrbitrapResolution="R120K",
    IsolationWindow=1,
    MaxITTimeInMS=200,
    Microscans=as.integer(40),
    AgcTarget=c(1e5, 5e5, 1e6)
)

cid <- expandMs2Conditions(
    MassList=targetMz,
    common,
    ActivationType="CID",
    CIDCollisionEnergy=c(NA, seq(7, 35, 7))
)
head(cid)
#                  MassList ActivationType OrbitrapResolution IsolationWindow
# 1 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 2 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 3 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 4 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 5 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 6 560.6/1 700.5/1 933.7/1            CID              R120K               1
#   MaxITTimeInMS Microscans AgcTarget CIDCollisionEnergy
# 1           200         40     1e+05                 NA
# 2           200         40     5e+05                 NA
# 3           200         40     1e+06                 NA
# 4           200         40     1e+05                  7
# 5           200         40     5e+05                  7
# 6           200         40     1e+06                  7

hcd <- expandMs2Conditions(
    MassList=targetMz,
    common,
    ActivationType="HCD",
    HCDCollisionEnergy=c(NA, seq(7, 35, 7))
)
head(hcd)
#                  MassList ActivationType OrbitrapResolution IsolationWindow
# 1 560.6/1 700.5/1 933.7/1            HCD              R120K               1
# 2 560.6/1 700.5/1 933.7/1            HCD              R120K               1
# 3 560.6/1 700.5/1 933.7/1            HCD              R120K               1
# 4 560.6/1 700.5/1 933.7/1            HCD              R120K               1
# 5 560.6/1 700.5/1 933.7/1            HCD              R120K               1
# 6 560.6/1 700.5/1 933.7/1            HCD              R120K               1
#   MaxITTimeInMS Microscans AgcTarget HCDCollisionEnergy
# 1           200         40     1e+05                 NA
# 2           200         40     5e+05                 NA
# 3           200         40     1e+06                 NA
# 4           200         40     1e+05                  7
# 5           200         40     5e+05                  7
# 6           200         40     1e+06                  7

etd <- expandMs2Conditions(
    MassList=targetMz,
    common,
    ActivationType="ETD",
    ETDReagentTarget=c(NA, 1e6, 5e6, 1e7),
    ETDReactionTime=c(NA, 2.5, 5, 10, 15, 30, 50),
    ETDSupplementalActivation=c("None", "ETciD", "EThcD"),
    ETDSupplementalActivationEnergy=c(NA, seq(7, 35, 7))
)
head(etd)
#                  MassList ActivationType OrbitrapResolution IsolationWindow
# 1 560.6/1 700.5/1 933.7/1            ETD              R120K               1
# 2 560.6/1 700.5/1 933.7/1            ETD              R120K               1
# 3 560.6/1 700.5/1 933.7/1            ETD              R120K               1
# 4 560.6/1 700.5/1 933.7/1            ETD              R120K               1
# 5 560.6/1 700.5/1 933.7/1            ETD              R120K               1
# 6 560.6/1 700.5/1 933.7/1            ETD              R120K               1
#   MaxITTimeInMS Microscans AgcTarget ETDReagentTarget ETDReactionTime
# 1           200         40     1e+05               NA              NA
# 2           200         40     5e+05               NA              NA
# 3           200         40     1e+06               NA              NA
# 4           200         40     1e+05            1e+06              NA
# 5           200         40     5e+05            1e+06              NA
# 6           200         40     1e+06            1e+06              NA
#   ETDSupplementalActivation ETDSupplementalActivationEnergy
# 1                      None                              NA
# 2                      None                              NA
# 3                      None                              NA
# 4                      None                              NA
# 5                      None                              NA
# 6                      None                              NA

uvpd <- expandMs2Conditions(
    MassList=targetMz,
    common,
    ActivationType="UVPD",
    UVPDActivationTime=c(NA, seq(5, 50, 5))
)
head(uvpd)
#                  MassList ActivationType OrbitrapResolution IsolationWindow
# 1 560.6/1 700.5/1 933.7/1           UVPD              R120K               1
# 2 560.6/1 700.5/1 933.7/1           UVPD              R120K               1
# 3 560.6/1 700.5/1 933.7/1           UVPD              R120K               1
# 4 560.6/1 700.5/1 933.7/1           UVPD              R120K               1
# 5 560.6/1 700.5/1 933.7/1           UVPD              R120K               1
# 6 560.6/1 700.5/1 933.7/1           UVPD              R120K               1
#   MaxITTimeInMS Microscans AgcTarget UVPDActivationTime
# 1           200         40     1e+05                 NA
# 2           200         40     5e+05                 NA
# 3           200         40     1e+06                 NA
# 4           200         40     1e+05                  5
# 5           200         40     5e+05                  5
# 6           200         40     1e+06                  5

ms2 <- topdownr:::.rbind(cid, hcd, etd, uvpd)
dim(ms2)
# [1] 1581   14
head(ms2)
#                  MassList ActivationType OrbitrapResolution IsolationWindow
# 1 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 2 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 3 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 4 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 5 560.6/1 700.5/1 933.7/1            CID              R120K               1
# 6 560.6/1 700.5/1 933.7/1            CID              R120K               1
#   MaxITTimeInMS Microscans AgcTarget CIDCollisionEnergy HCDCollisionEnergy
# 1           200         40     1e+05                 NA                 NA
# 2           200         40     5e+05                 NA                 NA
# 3           200         40     1e+06                 NA                 NA
# 4           200         40     1e+05                  7                 NA
# 5           200         40     5e+05                  7                 NA
# 6           200         40     1e+06                  7                 NA
#   ETDReagentTarget ETDReactionTime ETDSupplementalActivation
# 1               NA              NA                      <NA>
# 2               NA              NA                      <NA>
# 3               NA              NA                      <NA>
# 4               NA              NA                      <NA>
# 5               NA              NA                      <NA>
# 6               NA              NA                      <NA>
#   ETDSupplementalActivationEnergy UVPDActivationTime
# 1                              NA                 NA
# 2                              NA                 NA
# 3                              NA                 NA
# 4                              NA                 NA
# 5                              NA                 NA
# 6                              NA                 NA
```

**Comment by sgibb** [comment]
There is no documentation yet but maybe you want to try the following code (if you like it I will clean it up and write the documentation):
```r
devtools::install_github("sgibb/topdownr@xml")
library("topdownr")

ms1 <- expandMs1Conditions(FirstMass=400, LastMass=1200, Microscans=as.integer(10))

targetMz <- cbind(mz=c(560.6, 700.5, 933.7), z=rep(1, 3))
common <- list(
    OrbitrapResolution="R120K",
    IsolationWindow=1,
    MaxITTimeInMS=200,
    Microscans=as.integer(40),
    AgcTarget=c(1e5, 5e5, 1e6)
)

cid <- expandMs2Conditions(
    MassList=targetMz,
    common,
    ActivationType="CID",
    CIDCollisionEnergy=seq(7, 35, 7)
)
hcd <- expandMs2Conditions(
    MassList=targetMz,
    common,
    ActivationType="HCD",
    HCDCollisionEnergy=seq(7, 35, 7)
)
etd <- expandMs2Conditions(
    MassList=targetMz,
    common,
    ActivationType="ETD",
    ETDReagentTarget=c(1e6, 5e6, 1e7),
    ETDReactionTime=c(2.5, 5, 10, 15, 30, 50),
    ETDSupplementalActivation=c("None", "ETciD", "EThcD"),
    ETDSupplementalActivationEnergy=seq(7, 35, 7)
)
uvpd <- expandMs2Conditions(
    MassList=targetMz,
    common,
    ActivationType="UVPD",
    UVPDActivationTime=seq(5, 50, 5)
)

exps <- createExperimentsFragmentOptimisation(
    ms1=ms1, cid, hcd, etd, uvpd,
    groupBy=c("AgcTarget", "replication"), nMs2perMs1=10, duration=0.5,
    replications=2, randomise=TRUE, massLabeling=TRUE
)

library("xml2")

xsd <- read_xml("https://raw.githubusercontent.com/sgibb/meth-modifications/dev/xsds/Calcium/3.1/MethodModifications.xsd")

for (i in seq(along=exps)) {
    fn <- paste0("method_", names(exps)[i], ".xml")
    write_xml(as_xml_document(list(MethodModifications=exps[[i]])), file=fn)
    if (xml_validate(read_xml(fn), xsd)) {
        message(fn, " is valid!")
    } else {
        stop(fn, " is invalid!")
    }
}
```

It would be great if you could test the resulting xml files. There are vaildated against the XSD but I am not sure that they could be read by the Thermo software.

**Comment by pavel-shliaha** [comment]
Two suggestions:

1) could you please explain why  you created a function expandMs2Conditions(). Why not simply go with expand grid?
2)  I still think that createExperimentsFragmentOptimisation() function should take MS2 parameters as a data.frame. I talked to some collegues today and people have some really bizzare applications, whereby they dont want to scan through the combinations, but have specific requirements (e.g. they want the Scan description to say a specific thing, or they only want UVPD at that particular AGC with this particular time). They might want to create a file in say Excel and then load it through read.csv and create a method. So forcing them to go through expand.grid()/expandMs2Conditions() is too restrictive

**Comment by sgibb** [comment]
> could you please explain why you created a function expandMs2Conditions(). Why not simply go with expand grid?

- `expand.grid` is not simple for most of the R users. At least most of the users will forget to set `stringsAsFactors=FALSE` which will subsequently result in errors in the xml export.
- `expandMs2Conditions` ensures that the `MassList` is used in a correct way.
- `expandMs2Conditions` ensures that you don't combine useless stuff or wrong values, e.g.

Correct way (please note that `expandMs2Conditions` returns a `data.frame`):
```r
ms2 <- expandMs2Conditions(
    MassList=cbind(500, 1),
    ActivationType="ETD",
    OrbitrapResolution=c("R30K", "R120K"),
    Microscans=as.integer(c(40, 80))
)
ms2
#   MassList ActivationType OrbitrapResolution Microscans
# 1    500/1            ETD               R30K         40
# 2    500/1            ETD              R120K         40
# 3    500/1            ETD               R30K         80
# 4    500/1            ETD              R120K         80

class(ms2)
# [1] "data.frame"
```

Use incorrect values or types for the settings (the method uses the information from the XSD):
```r
expandMs2Conditions(
    MassList=cbind(500, 1),
    ActivationType="ETD",
    OrbitrapResolution=c("R1M", "R120K"),
    Microscans=c("foo", "bar"))
)
# Error in .validateMsSettings(type = ActivationType, settings) :
#   OrbitrapResolution could not be 'R1M'. Should be one of 'R15K, R30K, R50K, R60K, R120K, R240K, R500K'.
#   Microscans should be of class 'integer' but is 'character'.
```

Use incorrect combination (ETD and UVPD settings):
```r
expandMs2Conditions(
    MassList=cbind(500, 1),
    ActivationType="ETD",
    UVPDActivationTime=10)
# Error in .validateMsSettings(type = ActivationType, settings) :
#   UVPDActivationTime is not a valid element of type 'MS2'/'ETD' and/or not defined in MethodModification.xsd.
#   Run `validMs2Settings()` for a complete list of possible settings.
```

These checks can't be done by `expand.grid` (ok, we could add a user-visible function `validateMyMs2Settings`).

> I still think that `createExperimentsFragmentOptimisation()` function should take MS2 parameters as a `data.frame`.

`createExperimentsFragmentOptimisation` expects one *MS1* `data.frame` and multiple *MS2* `data.frame`s:

```r
exps <- createExperimentsFragmentOptimisation(
    ms1 = data.frame(FirstMass=500, LastMass=1000),
    ## MS2

    ## use ms2 data.frame from above
    ms2,
    ## add some other data.frame
    data.frame(MassList="500/1", Microscans=50, ActivationType="ETD", stringsAsFactors=FALSE),

    ## other arguments
    groupBy="Microscans"
)
```

> [...] or they only want UVPD at that particular AGC with this particular time [...]

```r
exps <- createExperimentsFragmentOptimisation(
    ms1 = data.frame(FirstMass=500, LastMass=1000),
    ## MS2

    ## use ms2 data.frame from above
    ms2,
    ## create some UVPD at that particular AGC
    data.frame(ActivationType="UVPD", AgcTarget=1e5, stringsAsFactors=FALSE),

    ## other arguments
    groupBy="ActivationType"
)
```

> [...] They might want to create a file in say Excel and then load it through read.csv and create a method.

As shown above that is possible and really easy.

```r
myCsvContent <- "
ActivationType, ETDReactionTime, UVPDActivationTime
UVPD,,1000
ETD,1000,
"
myCsvSettings <- read.csv(text=myCsvContent, stringsAsFactors=FALSE)
myCsvSettings
#   ActivationType ETDReactionTime UVPDActivationTime
# 1           UVPD              NA               1000
# 2            ETD            1000                 NA

exps <- createExperimentsFragmentOptimisation(
    ms1 = data.frame(FirstMass=500, LastMass=1000),
    ## MS2
    myCsvSettings,
    ## other arguments
    groupBy="ActivationType"
)
```
(needs the most recent version from github because before you were forced to add a MassList)

> So forcing them to go through `expand.grid()`/`expandMs2Conditions()` is too restrictive.

IMHO it is extrem user-friendly and flexible, isn't it?

**Comment by pavel-shliaha** [comment]
@sgibb yep you are right of course. So basically this is a very user friendly way to make things idiot proof, but you can also still use a csv file

Could you please explain how you got the checks to work. E.g.:

UVPDActivationTime is not a valid element of type 'MS2'/'ETD' and/or not defined in MethodModification.xsd.

did you manually write this, or did you import it from XSD schema?

**Comment by sgibb** [comment]
I parse the XSD with some functions in https://github.com/sgibb/topdownr/blob/xml/R/xml-functions.R. These functions create a matrix that is visible with `validMs1Settings()` and `validMs2Settings()`. Finally I compare the input against these matrices: https://github.com/sgibb/topdownr/blob/03ab55d0a9cea7ba97b82071ff8c6b77047b7a7e/R/experiment-functions.R#L281-L329

Ok, I will clean up the functions, write the documentation and update the vignette (and I will deprecate the old `writeModificationMethodXml` function).

**Comment by pavel-shliaha** [comment]
I have tested a method with no splitting of experiments into start and end times (i.e. all MS2 experiments co-exist throughout the run) and it appears the instrument is executing the experiments in the correct order without missing any. 

![for_sebastian](https://user-images.githubusercontent.com/1895805/47116273-74522000-d261-11e8-81fe-3992aecd8785.PNG)

In light of this can I request:

1) introduce a new argument, e.g. splitExperimentsByTime. If FALSE then dont use the 

'''<StartTimeMin></StartTimeMin>
<EndTimeMin></EndTimeMin>'''

2) make targetMz argument in expandMS2Conditions optional. I.e. if nothing is specified the script simply does not change the targeted mz

**Comment by sgibb** [comment]
1. Adding a switch to (not) use *StartTimeMin*/*EndTimeMin* is easy. But is `splitExperimentsByTime` a good name. Are the experiments really splitted? What about just `useTime` or `useStartEndTime`?

2. Making `TargetMz` optional: I will do. 

BTW: Regarding the MS3 scans: should I rename `expandMs2Conditions` into `expandMsnConditions`?

**Comment by sgibb** [comment]
Sorry for the delay. I have to ask another question. You suggested to count from
1 to *number of conditions* and repeat until the method ends. If I compare this
approach to *FilterString* it won't work:

```r
header <- .readScanHeadsTable(
    "../topdownrdata/inst/extdata/20170629_myo/header/myo_1211_ETDReagentTarget_1e6_1.txt.gz"
)

## conditions based on FilterString
header$Condition
#   [1]   1   1   2   2   3   3   4   4   5   5   6   6   7   7   8   8   9   9
#  [19]  10  10  11  11  12  12  13  14  14  15  15  16  17  17  18  18  19  20
#  [37]  20  21  21  22  23  23  24  24  25  26  26  27  27  28  29  29  30  31
#  [55]  31  32  32  33  34  34  35  36  36  37  37  38  39  39  40  40  41  42
#  [73]  42  43  43  44  45  45  46  47  47  48  48  49  50  50  51  51  52  53
#  [91]  53  54  55  55  56  56  57  58  58  59  60  60  61  62  62  63  64  64
# [109]  65  66  66  67  67  68  69  69  70  71  71  72  73  73  74  75  75  76
# [127]  77  77  78  78  79  79  80  80  81  81  82  83  83  84  84  85  85  86
# [145]  86  87  87  88  89  89  90  90  91  92  93  93  94  94  95  96  96  97
# [163]  98  98  99 100 100 101 102 102 103 103 104 105 105 106 107 107 108 109
# [181] 109 110 111 111 112 113 113 114 115 115 116 116 117 118 118 119 120 120
# [199] 121 122 122 123 124 125 125 126 127 127 128 129 129 130 131 131 132 133
# [217] 133 134 135 135 136 137 137 138 139 139 140 141 141 142 143 143 144 145
# [235] 146 146 147 148 148 149 150 151 151 152 153 153 154 154 155 156 156 157
# [253] 157 158 158 159 159 160 160 161 162 162 163 163 164 165 165 166 167 167
# [271] 168 169 169 170 171 171 172 173 173 174 175 175 176 177 177 178 179 179
# [289] 180 181 181 182 183 184 184 185 186 186 187 188 188 189 190 190 191 192
# [307] 193 193 194 195 195 196 197 197 198 199 199 200 201 202 202 203 204 204
# [325] 205 206 206 207 208 209 209 210 211 211 212 213 214 214 215 216 217 217
# [343] 218 219 219 220 221 222 222 223 224 225 225 226 227 227 228

## your suggestion, assuming 2 conditions
cd <- rep(seq_len(ceiling(nrow(header) / 2L)), each=2)[seq_len(nrow(header))]
#   [1]   1   1   2   2   3   3   4   4   5   5   6   6   7   7   8   8   9   9
#  [19]  10  10  11  11  12  12  13  13  14  14  15  15  16  16  17  17  18  18
#  [37]  19  19  20  20  21  21  22  22  23  23  24  24  25  25  26  26  27  27
#  [55]  28  28  29  29  30  30  31  31  32  32  33  33  34  34  35  35  36  36
#  [73]  37  37  38  38  39  39  40  40  41  41  42  42  43  43  44  44  45  45
#  [91]  46  46  47  47  48  48  49  49  50  50  51  51  52  52  53  53  54  54
# [109]  55  55  56  56  57  57  58  58  59  59  60  60  61  61  62  62  63  63
# [127]  64  64  65  65  66  66  67  67  68  68  69  69  70  70  71  71  72  72
# [145]  73  73  74  74  75  75  76  76  77  77  78  78  79  79  80  80  81  81
# [163]  82  82  83  83  84  84  85  85  86  86  87  87  88  88  89  89  90  90
# [181]  91  91  92  92  93  93  94  94  95  95  96  96  97  97  98  98  99  99
# [199] 100 100 101 101 102 102 103 103 104 104 105 105 106 106 107 107 108 108
# [217] 109 109 110 110 111 111 112 112 113 113 114 114 115 115 116 116 117 117
# [235] 118 118 119 119 120 120 121 121 122 122 123 123 124 124 125 125 126 126
# [253] 127 127 128 128 129 129 130 130 131 131 132 132 133 133 134 134 135 135
# [271] 136 136 137 137 138 138 139 139 140 140 141 141 142 142 143 143 144 144
# [289] 145 145 146 146 147 147 148 148 149 149 150 150 151 151 152 152 153 153
# [307] 154 154 155 155 156 156 157 157 158 158 159 159 160 160 161 161 162 162
# [325] 163 163 164 164 165 165 166 166 167 167 168 168 169 169 170 170 171 171
# [343] 172 172 173 173 174 174 175 175 176 176 177 177 178 178 179
```

If we use *FilterString* we have some conditions with just one run (instead of two). How could we solve this? Are there any (combination of) columns in the header file that we could use instead of *FilterString*? 

E.g. we use the following **after** assembling the whole object
```r
sampleColumns=c(
    "Mz",                              # experiments.csv
    "AgcTarget",                       # experiments.csv
    "EtdReagentTarget",                # experiments.csv
    "EtdActivation",                   # header.txt
    "CidActivation",                   # header.txt
    "HcdActivation",                   # header.txt
    "UvpdActivation"                   # header.txt
)
```
Using just the *Activation columns from the header is not enough to distinguish the conditions.

**Comment by pavel-shliaha** [comment]
Yes, it will not work on the data we already acquired. It only works if all the experiments have overlapping and identical allocated method time. 

E.g. before (new solution wont work): 

![before](https://user-images.githubusercontent.com/1895805/48029974-ed051780-e14f-11e8-9d06-65f34533df28.PNG)

Now (new solution will work): all the experiments have the same RT and will be executed seqeuntially

![now](https://user-images.githubusercontent.com/1895805/48029981-f0989e80-e14f-11e8-8ed6-a0c35aed2dec.PNG)

**Comment by sgibb** [comment]
Again sorry for the long silence. I rewrote the functions slightly and add some
documentation.

Main changes:
- `expandMs2Conditions()` was renamed to `expandTms2Conditions()`.
- `massLabeling` was removed for `createExperimentsFragmentOptimisation()`.
- Support for `<ScanDescription>` added.
- `MassList` is now optional.
- `StartTimeMin`/`EndTimeMin` are not set if the newly introduced
`scanDuration` argument is zero (we discussed `useStartEndTime` before but I don't like two arguments (`useStartEndTime`, `scanDuration`) for one setting).
- `writeMethodXmls` gains a new `exps` argument for the new tree-like `list`
generated by `createExperimentsFragmentOptimisation()`. Beside `exps`, `pattern`
and `verbose` all other arguments are **deprecated** now and will be removed
after the next bioc release (so `writeMethodXmls` will really just write the
                             xmls and don't do any combination stuff).

Here is the current way to create method.xml files. Could you please test this?
(I had not installed the newest ThermoWorkstation on my Windows machine yet.)

```r
devtools::install_github("sgibb/topdownr@xml")
library("topdownr")

ms1 <- expandMs1Conditions(FirstMass=400, LastMass=1200, Microscans=as.integer(10))

targetMz <- cbind(mz=c(560.6, 700.5, 933.7), z=rep(1, 3))
common <- list(
    OrbitrapResolution="R120K",
    IsolationWindow=1,
    MaxITTimeInMS=200,
    Microscans=as.integer(40),
    AgcTarget=c(1e5, 5e5, 1e6)
)

cid <- expandTms2Conditions(
    MassList=targetMz,
    common,
    ActivationType="CID",
    CIDCollisionEnergy=seq(7, 35, 7)
)
hcd <- expandTms2Conditions(
    MassList=targetMz,
    common,
    ActivationType="HCD",
    HCDCollisionEnergy=seq(7, 35, 7)
)
etd <- expandTms2Conditions(
    MassList=targetMz,
    common,
    ActivationType="ETD",
    ETDReagentTarget=c(1e6, 5e6, 1e7),
    ETDReactionTime=c(2.5, 5, 10, 15, 30, 50),
    ETDSupplementalActivation=c("None", "ETciD", "EThcD"),
    ETDSupplementalActivationEnergy=seq(7, 35, 7)
)
uvpd <- expandTms2Conditions(
    MassList=targetMz,
    common,
    ActivationType="UVPD",
    ## stupid space suffix, because Thermo didn't fixed it
    "UVPDActivationTime "=seq(5, 50, 5)
)

exps <- createExperimentsFragmentOptimisation(
    ms1=ms1, cid, hcd, etd, uvpd,
    groupBy=c("AgcTarget", "replication"), nMs2perMs1=10,
    replications=2, randomise=TRUE
)

writeMethodXmls(exps=exps)

## using Start/EndTimeMin (scanDuration > 0)
exps <- createExperimentsFragmentOptimisation(
    ms1=ms1, cid, hcd, etd, uvpd,
    groupBy=c("AgcTarget", "replication"), nMs2perMs1=10,
    scanDuration=0.5,
    replications=2, randomise=TRUE
)

writeMethodXmls(exps=exps)
```

TODO: Adapt the `vignette` to the new version of Thermo software and to the new way of creating method files (but I wait until you verify that this is working and you like it).

**Comment by sgibb** [comment]
/remind me to *defunct*/*remove* useless arguments of `writeMethodXmls` in May 2019

**Comment by pavel-shliaha** [comment]
Tested it. Seems to have a bug. I expected to have 6 files

Writing method-1e+05:1.xml
Writing method-1e+05:2.xml
Writing method-1e+06:1.xml
Writing method-1e+06:2.xml
Writing method-5e+05:1.xml
Writing method-5e+05:2.xml

instead I got 3:

method-1e+05
method-1e+06
method-5e+05

they dont have any extension

**Comment by sgibb** [comment]
That's wired. It is working for me (I got the six files you are mentioned.). Are you using exactly the same code? Is ":" a special character on Windows? I will try to reproduced it on my virtual Windows image.

**Comment by pavel-shliaha** [comment]
I will send you the exps vobject shortly

**Comment by sgibb** [comment]
I fixed the filenames. I wasn't aware that the colon is not allowed on Windows. Sorry. JFTR: [filename convention on Windows](https://docs.microsoft.com/de-de/windows/desktop/FileIO/naming-a-file#naming_conventions).

Please try again.

**Comment by pavel-shliaha** [comment]
Tested it. The XMLs are created succesfully, but there is a bug: MassList is a child of TMSnScan now and not of Experiment.

**Comment by pavel-shliaha** [comment]
2 more things:

1)

 <Modification Order="2">
    <CopyAndAppendExperiment SourceExperimentIndex="1"/>
    <Experiment ExperimentIndex="1"/>
  </Modification>

you do not need to have <Experiment ExperimentIndex="1"/>

the copying works with just 

 <Modification Order="2">
    <CopyAndAppendExperiment SourceExperimentIndex="1"/>
    <Experiment ExperimentIndex="1"/>
  </Modification>

2) XMLMethodChanger actually modifies .meth, not create it from scratch. It means that in the method you already have one MS1 and one MS2 scan. Thus if you need series of MS1 + 10 MS2, you need to first start by adding 9 MS2 (not 10 as I can see in your code)

**Comment by pavel-shliaha** [comment]
ok I tested it . This works. The only problem is in your example ETciD is created as part of ETD as shown below:

```
etd <- expandTms2Conditions(
    ActivationType="ETD",
    ETDReactionTime= 1:2,
    ETDSupplementalActivation=c("None", "ETciD"),
    ETDSupplementalActivationEnergy=1:2
)
```

lets designate conditions by number_number, whereby first number is ETD reaction time and second is the energy of supplemental activation).

what I want here is 2 ETD conditions (1_0, 2_0) ànd 4  ETciD conditions (1_1, 1_2, 2_1, 2_2) 
what I get is 4 ETD conditions (1_0, 1_0, 2_0, 2_0) and 4 ETciD conditions  (1_1, 1_2, 2_1, 2_2) 

what you need to do is create separate etd and etcid

```
etd <- expandTms2Conditions(
    ActivationType="ETD",
    ETDReactionTime= 1:2,
)

etcid <- expandTms2Conditions(
    ActivationType="ETD",
    ETDReactionTime= 1:2,
    ETDSupplementalActivation="ETciD",
    ETDSupplementalActivationEnergy=1:2
)
```

**Comment by sgibb** [comment]
Could you please check the vignette: https://sgibb.github.io/topdownr/articles/data-generation.html

BTW: I moved all this to the master branch. That means you could use `devtools::install_github("sgibb/topdownr")` now.

**Comment by sgibb** [comment]
/remind me to remove useless arguments of `writeMethodXmls` and `defaultMs{1,2}Settings()` in November 2019.

**Comment by sgibb** [comment]
done in 1.9.1 (2a64f5cd77b62d8cf101ea935cc603ccb6b1bc8c)
