### ISSUE TITLE
Explanation of the method file for fragmentation optimisation

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#78]
@sgibb asked me to have a look into an error to create a method, which prompts me to create this entry that we should add to wiki. 

When performing fragmentation optimisation we are using the following file as a template. Note that 2 experiments are necessary MS1 and targeted MS2 (tMS2)

![tms2](https://user-images.githubusercontent.com/1895805/46373879-85126b80-c68f-11e8-93ba-a2807e94e467.PNG)

The MS1 has experiment index 0 and tMS2 has experiment index 1.

**Comment by sgibb** [comment]
I would not create a wiki entry but modify the [Data Generation vignette](https://sgibb.github.io/topdownr/articles/data-generation.html) (which we have to update to 3.1 workflow anyway)

**Comment by pavel-shliaha** [comment]
sorry, I meant vignette of course
