### ISSUE TITLE
new way of reading the data in

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#80]
So the new approach to make the method is now working. Compared to the previous there are 3 relevant modifications:

1) we no longer split the experiments (fragmentation conditions) by time. This ensures experiments are always executed in order
2) we can have several different mz targeted for fragmentation with a particular experiment   (fragmentation conditions). 
3) we got access to "Scan Description" parameter and we now label the conditions with "C0X" schema. This results in "Scan.Description" column now appearing in scanHeadsMan ".txt" output

NOTE: even though experiments are executed in order having different number of mz in each experiment precludes direct assignment of scans to experiment simply by order. For example if we have 5 scans, they could be condition_1_mz_1, condition_1_mz_2, condition_1_mz_3, condition_2_mz_1, conditions_3_mz_1

Thus the most straightforward way is to match scans to experiments (conditions) by using the "Scan.Description" column in ".txt" file and simply taking the corresponding line in csv file, where MS1 scans have been removed. I will provide the example shortly.

**Comment by pavel-shliaha** [comment]
The files are in 

Google Drive\example_files_for_topDown\topdownr_2\new_condition_labelling

let me know if you have acces

**Comment by sgibb** [comment]
There was no fasta file in this folder. I used this one: https://www.uniprot.org/uniprot/P09919.fasta
Also there are 756 scans in the scanHeadsman output but just 36 in the experiment.csv. How to match them? I now used a combination of `ScanDescription` and `SelectedMass1` to define a single condition (as you suggested above). But even then there are ~ 7 replicates.

Could you give it a try?
```r
devtools::install_github("sgibb/topdownr@newConditions")
tds <- readTopDownFiles("new_condition_labeling", conditions="ScanDescription")
```

**Comment by sgibb** [comment]
Does that changed as well?:
> More than 150 experiments might cause the MS device to become unresponsive. Choose other ‘groupBy’ parameters to reduce number of experiments per file.

**Comment by pavel-shliaha** [comment]
1) My apologies, it appears that both fasta and mzML are missing I will ask Masa to upload these
2) Yes there are many replicates here. I guess Masa needed these much
